export const CHANGE_WORKSPACE = "CHANGE_WORKSPACE"
export const CLOSE_DROPDOWN = "CLOSE_DROPDOWN"
export const OPEN_DROPDOWN = "OPEN_DROPDOWN"

export const CHANGE_BREAKPOINT = "CHANGE_BREAKPOINT"
export const TOGGLE_LEFT_SIDEBAR = "TOGGLE_LEFT_SIDEBAR"
export const TOGGLE_RIGHT_SIDEBAR = "TOGGLE_RIGHT_SIDEBAR"

export const LOAD_PRESENTATION = "LOAD_PRESENTATION"
export const ADD_ASSET = "ADD_ASSET"
export const ADD_TO_PRESENTATION = "ADD_TO_PRESENTATION"
export const SELECT_ITEM  = "SELECT_ITEM"
export const OPEN_MODAL = 'OPEN_MODAL'
export const CLOSE_MODAL = 'CLOSE_MODAL'
export const TOGGLE_DRAGGING = "TOGGLE_DRAGGING"
export const ON_DRAG = "ON_DRAG"
export const ON_DROP = "ON_DROP"

export const SELECT_ASSET = "SELECT_ASSET"
export const SELECT_COMPONENT = "SELECT_COMPONENT"
