export const CHANGE_WORKSPACE = "CHANGE_WORKSPACE"
export const CLOSE_DROPDOWN = "CLOSE_DROPDOWN"
export const OPEN_DROPDOWN = "OPEN_DROPDOWN"

export const CHANGE_BREAKPOINT = "CHANGE_BREAKPOINT"
export const TOGGLE_LEFT_SIDEBAR = "TOGGLE_LEFT_SIDEBAR"
export const TOGGLE_RIGHT_SIDEBAR = "TOGGLE_RIGHT_SIDEBAR"

export const LOAD_PRESENTATION = "LOAD_PRESENTATION"
export const ADD_ASSET = "ADD_ASSET"
export const ADD_TO_PRESENTATION = "ADD_TO_PRESENTATION"